### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by sherson** [umts/BusInfoBoard#22]
Maybe reload page periodically?

![businfoboard-out-of-memory](https://cloud.githubusercontent.com/assets/409008/6062656/720f8b0e-ad1f-11e4-93f1-783dac34dad5.jpg)

**Comment by werebus** [comment]
https://developer.chrome.com/devtools/docs/javascript-memory-profiling

**Comment by bcspragu** [comment]
Using the tools you linked to, I can totally confirm, with science, that we do indeed have a memory leak somewhere. The profiling tools haven't helped me find it yet, but as expected it happens on each refresh. Attached is science.

![mem](https://cloud.githubusercontent.com/assets/2402010/6920428/29da4120-d78c-11e4-95cf-987302f90dd5.png)

**Comment by bcspragu** [comment]
Ok, so I had previously emailed about the [streamlined feed](http://avail.findsherson.com/?stop=64&stop=63), and now I've added a [proof-of-concept](http://avail.findsherson.com/board) that uses it. The code is accessible [here](https://github.com/bcspragu/BusProxy/blob/master/js/main.js). A lightweight data-binding framework maps the feed to the display, and the resulting code is only 35 lines, and even with all of the features re-implemented, it wouldn't be anywhere near the existing 471 lines. This should hopefully reduce the stress on the Pi, because I trust the data-binding framework to handle the DOM better than we do.<sup><sup><sup>A potentially questionable assumption, I know</sup></sup></sup>

**Comment by bcspragu** [comment]
Also, why did PVTA change the Route 30 color to "banana-left-in-the-sun yellow"?

**Comment by sherson** [comment]
Contrast was too low with white text (another option was to use black text, but then it'd be inconsistent with the other routes).
