### ISSUE TITLE
Times incorrect in ILC?

### ISSUE THREAD

**Issue by werebus** [umts/BusInfoBoard#62]
Departure estimates are correct, but the "actual" time of the departure appears to be off by 5 hours.  5 hours is an interesting amount of time to be off by, perhaps the new code in #54 is not dealing with the machine locale correctly?  There's a chance that the time-zone on the RPi is UTC...?

**Comment by dfaulken** [comment]
Hmm, I know how to "fix" this, but it seems undesirable to write our code to infer its timezone from the timezone in the timestamps in the Avail endpoint data rather than the timezone the machine's set to be in. That is, if our Avail endpoint's on one side of Indiana, returning times local to it, and we're on the other side of Indiana, shouldn't we display local (to the board) times when buses are coming?

Is the real bug here not that the RPi is localized to somewhere other than where it actually is? And that our interval parsing functions just assumes the timezones are the same? Or am I off base here?

**Comment by sherson** [comment]
The pi was set to UTC. As a temporary fix, I changed it to EDT via ssh and sudo raspi-config.

Talked to the RO and got confirmation from a driver that the times on the sign are currently correct.

**Comment by werebus** [comment]
Yes, you're correct. I think.

I opened this bug on the way out the door to make sure it was documented,
but I think that the behavior is actually correct.

I'll take a look tomorrow.

**Comment by werebus** [comment]
Fixed by @sherson.

I think the behavior of "show the departure localized to wherever the board is located" is arguably correct.  Even though it's probably a rare occurrence that a departure board and the transit agency are in two different time zones.
